from gpnet.workflow import simdata, predictor, visualizer, selector
import argparse


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(title="sub commands")

    parser_simulator = subparsers.add_parser('simulator', help='Simulate genotypes and phenotype of a population')
    parser_simulator.add_argument('-o', '--outdir', help='Output directory', required=True)
    parser_simulator.add_argument('-r', '--round', help='Simulate round, default=1000',
                                  type=int, default=1000)
    parser_simulator.add_argument('-s', '--sites', help='Simulate variant site count, default=100',
                                  type=int, default=100)
    parser_simulator.add_argument('-a', '--avg_types', help='Average of variant types, default=5',
                                  type=int, default=5)
    parser_simulator.add_argument('-n', '--noise',
                                  help='Noise ratio of sites, these sites have lower genomic value'
                                       'than others , default=0.0 and less than 1',
                                  type=float, default=0.0)
    parser_simulator.add_argument('-c', '--samples', help='Simulate sample count, default=100',
                                  type=int, default=100)
    parser_simulator.add_argument('-b', '--hybrid',
                                  help='Means simulate a hybrid population, if this parameter is setting',
                                  action='store_true')
    parser_simulator.add_argument('-p', '--parent',
                                  help='Parent counts for simulating hybrid population, only effect when hybrid is '
                                       'setting, default=10',
                                  type=int, default=10)
    parser_simulator.add_argument('-t', '--thread', help='Threads, default=10', type=int, default=10)
    parser_simulator.set_defaults(func=simdata.main)

    parser_predictor = subparsers.add_parser('predictor', help='Predict best genotype with population')
    parser_predictor.add_argument('-i', '--input', help='Input data file or list file', required=True)
    parser_predictor.add_argument('-w', '--weight', help='Weight file or list file, required if data '
                                                         'is generated by gpnet.py simulator')
    parser_predictor.add_argument('-o', '--output', help='Output file or directory', required=True)
    parser_predictor.add_argument('--single', help='Input file is a single sample file',
                                  action='store_true')
    parser_predictor.add_argument('-m', '--method', help='Predict method, can be: CWNET, MLR, XGB, '
                                                         'default=CWNET',
                                  choices=['CWNET', 'MLR', 'XGB'], default="CWNET")
    parser_predictor.add_argument('-l', '--lower', help='Means lower phenotype is better, '
                                                        'if this parameter is setting',
                                  action='store_true')
    parser_predictor.add_argument('--normalization',
                                  help='Normalization weight of nodes and edges with min-max, '
                                       'if this parameter is setting',
                                  action='store_true')
    parser_predictor.add_argument('-t', '--thread', help='Threads, default=10, '
                                                         'if input single file, auto set to 1',
                                  type=int, default=10)
    parser_predictor.set_defaults(func=predictor.main)

    parser_selector = subparsers.add_parser('selector', help='Get most effective genes from network '
                                                             'generated by CWNET')
    parser_selector.add_argument('-i', '--input', help='Input result file of CWNET', required=True)
    parser_selector.add_argument('-o', '--output', help='Output list file of best genes', required=True)
    parser_selector.add_argument('-n', '--count', help='Gene counts for selecting, default=5',
                                 type=int, default=5)
    parser_selector.add_argument('-l', '--lower',
                                 help='Means lower phenotype is better, if this parameter is setting',
                                 action='store_true')
    parser_selector.set_defaults(func=selector.main)

    parser_visualizer = subparsers.add_parser('visualizer', help='Visualize network generated by CWNET')
    parser_visualizer.add_argument('-i', '--input', help='Input result file of CWNET', required=True)
    parser_visualizer.add_argument('-o', '--output', help='Output html file of network', required=True)
    parser_visualizer.add_argument('--node_cmap', help="Colormap for nodes, default=\"Oranges\"",
                                   default="Oranges")
    parser_visualizer.add_argument('--edge_cmap', help="Colormap for edges, default=\"Greens\"",
                                   default="Greens")
    parser_visualizer.add_argument('--node_ratio',
                                   help="Ratio of node size, higher means smaller node size, default=3.0", type=float,
                                   default=3.0)
    parser_visualizer.add_argument('--edge_ratio',
                                   help="Ratio of edge width, higher means thinner edge width, default=20.0",
                                   type=float, default=20.0)
    parser_visualizer.add_argument('-l', '--lower',
                                   help='Means lower phenotype is better, if this parameter is setting',
                                   action='store_true')
    parser_visualizer.set_defaults(func=visualizer.main)

    try:
        args = parser.parse_args()
        args.func(args)
    except AttributeError:
        parser.print_help()
