#!/usr/bin/env python3
from gpnet.workflow import simdata, predictor
import argparse


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(title="sub commands")

    parser_simulator = subparsers.add_parser('simulator', help='Simulate genotypes and phenotype of a population')
    parser_simulator.add_argument('-o', '--outdir', help='Output directory', required=True)
    parser_simulator.add_argument('-r', '--round', help='Simulate round, default=1000', type=int, default=1000)
    parser_simulator.add_argument('-s', '--sites', help='Simulate variant site count, default=100',
                                  type=int, default=100)
    parser_simulator.add_argument('-m', '--max_types', help='Max variant types, default=10', type=int, default=10)
    parser_simulator.add_argument('-n', '--noise', help='Noise ratio of sites, these sites have lower genomic value'
                                                        'than others and not appear in co-effect sites'
                                                        ', default=0.0 and less than 1', type=float, default=0.0)
    parser_simulator.add_argument('-c', '--samples', help='Simulate sample count, default=100', type=int, default=100)
    parser_simulator.add_argument('-t', '--thread', help='Threads, default=10', type=int, default=10)
    parser_simulator.set_defaults(func=simdata.main)

    parser_predict = subparsers.add_parser('predictor', help='Predict best genotype with population')
    parser_predict.add_argument('-i', '--input', help='Input data file or list file', required=True)
    parser_predict.add_argument('-w', '--weight', help='Weight file or list file, required while data '
                                                       'is generated by gpnet.py simulator')
    parser_predict.add_argument('-o', '--output', help='Output file or directory', required=True)
    parser_predict.add_argument('--single', help='Input file is a single sample file', action='store_true')
    parser_predict.add_argument('-m', '--method', help='Predict method, can be: MLR, CWNET, XGB, default=MLR',
                                default="MLR")
    parser_predict.add_argument('-t', '--thread', help='Threads, default=10, if input single file, auto set to 1',
                                type=int, default=10)
    parser_predict.set_defaults(func=predictor.main)

    try:
        args = parser.parse_args()
        args.func(args)
    except AttributeError:
        parser.print_help()


if __name__ == "__main__":
    main()
