from gpnet.workflow import predict_data, visualize_data
from gpnet.workflow import simulate_data, select_data
from gpnet.__version__ import __version__


def get_opts(parser):
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version="%(prog)s {version}".format(version=__version__),
    )
    subparsers = parser.add_subparsers(title="sub commands")

    parser_simulator = subparsers.add_parser(
        "simulator", help="Simulate genotypes and phenotype of a population"
    )
    parser_simulator.add_argument(
        "-o", "--outdir", help="Output directory", required=True
    )
    parser_simulator.add_argument(
        "-r", "--round", help="Simulate round, default=1000", type=int, default=1000
    )
    parser_simulator.add_argument(
        "-s",
        "--sites",
        help="Simulate variant site count, default=100",
        type=int,
        default=100,
    )
    parser_simulator.add_argument(
        "-a",
        "--avg_types",
        help="Average of variant types, default=5",
        type=int,
        default=5,
    )
    parser_simulator.add_argument(
        "-n",
        "--noise",
        help="Noise ratio of sites, these sites have lower genomic value"
        "than others , default=0.0 and less than 1",
        type=float,
        default=0.0,
    )
    parser_simulator.add_argument(
        "-c",
        "--samples",
        help="Simulate sample count, default=100",
        type=int,
        default=100,
    )
    parser_simulator.add_argument(
        "-b",
        "--hybrid",
        help="Means simulate a hybrid population, if this parameter is setting",
        action="store_true",
    )
    parser_simulator.add_argument(
        "-p",
        "--parent",
        help="Parent counts for simulating hybrid population, only effect when hybrid is "
        "setting, default=10",
        type=int,
        default=10,
    )
    parser_simulator.add_argument(
        "--seed",
        help="Random seed for simulating data, default=None",
        type=int,
        default=None,
    )
    parser_simulator.add_argument(
        "-t", "--thread", help="Threads, default=10", type=int, default=10
    )
    parser_simulator.set_defaults(func=simulate_data.main)

    parser_predictor = subparsers.add_parser(
        "predictor", help="Predict best genotype with population"
    )
    parser_predictor.add_argument(
        "-i", "--input", help="Input data file or list file", required=True
    )
    parser_predictor.add_argument(
        "-w",
        "--weight",
        help="Weight file or list file, required if data "
        "is generated by wpnet.py simulator",
    )
    parser_predictor.add_argument(
        "-o", "--output", help="Output file or directory", required=True
    )
    parser_predictor.add_argument(
        "--single", help="Input file is a single sample file", action="store_true"
    )
    parser_predictor.add_argument(
        "-m",
        "--method",
        help="Predict method, can be: CWNET, CWNET_FR, MLR, default=CWNET_FR",
        choices=["CWNET", "CWNET_FR", "MLR"],
        default="CWNET_FR",
    )
    parser_predictor.add_argument(
        "--lower",
        help="Means lower phenotype is better, " "if this parameter is setting",
        action="store_true",
    )
    parser_predictor.add_argument(
        "--normalization",
        help="Normalization weight of nodes and edges with min-max, "
        "if this parameter is setting",
        action="store_true",
    )
    parser_predictor.add_argument(
        "--store_iter", help="Store iteration file if is setting", action="store_true"
    )
    parser_predictor.add_argument(
        "--top_edges",
        type=int,
        default=5000,
        help="Maximum number of edges to attempt to search (Max Edges)",
    )
    parser_predictor.add_argument(
        "--min_edge_count",
        type=int,
        default=2,
        help="Minimum frequency of edge appearance",
    )
    parser_predictor.add_argument(
        "--step_size",
        type=int,
        default=50,
        help="Step size when searching for edges (default is 50)",
    )
    parser_predictor.add_argument(
        "--optim",
        help="Optimize method for predicting best one, default=SA",
        type=str,
        choices=["SA", "GA"],
        default="SA",
    )
    parser_predictor.add_argument(
        "--iter",
        help="Number of iterations for SA algorithm, default=100",
        type=int,
        default=100,
    )
    parser_predictor.add_argument(
        "--alpha",
        help="Alpha value for SA algorithm, default=0.99",
        type=float,
        default=0.99,
    )
    parser_predictor.add_argument(
        "--n_gen",
        help="Number of generations for GA algorithm, default=1000",
        type=int,
        default=1000,
    )
    parser_predictor.add_argument(
        "--pop_size",
        help="Number of individuals in population for GA algorithm, default=200",
        type=int,
        default=200,
    )
    parser_predictor.add_argument(
        "--cross_rate",
        help="Cross rate of crossover for GA algorithm, default=0.8",
        type=float,
        default=0.8,
    )
    parser_predictor.add_argument(
        "--mutation_rate",
        help="Mutation rate for GA algorithm, default=0.05",
        type=float,
        default=0.05,
    )
    parser_predictor.add_argument(
        "--seed",
        help="Random seed for predictor, default=None",
        type=int,
        default=None,
    )
    parser_predictor.add_argument(
        "-t",
        "--thread",
        help="Threads, default=10, " "if input single file, auto set to 1",
        type=int,
        default=10,
    )
    parser_predictor.set_defaults(func=predict_data.main)

    parser_selector = subparsers.add_parser(
        "selector",
        help="Get most effective genes from network generated by CWNET/CWNET_FR",
    )
    parser_selector.add_argument(
        "-i", "--input", help="Input result file of CWNET/CWNET_FR", required=True
    )
    parser_selector.add_argument(
        "-m", "--model", help="Model file generated by CWNET_FR"
    )
    parser_selector.add_argument(
        "--mat",
        help="Input mat file which was used with predictor, if set, the selected combination "
        "could be found in population",
    )
    parser_selector.add_argument(
        "-o", "--output", help="Output list file of best genes", required=True
    )
    parser_selector.add_argument(
        "-n",
        "--count",
        help="Gene counts for selecting, default=5",
        type=int,
        default=5,
    )
    parser_selector.add_argument(
        "--lower",
        help="Means lower phenotype is better, if this parameter is setting",
        action="store_true",
    )
    parser_selector.add_argument(
        "--method",
        help="Method for selecting best n alleles, default=Simple",
        type=str,
        choices=["Simple", "SA"],
        default="Simple",
    )
    parser_selector.add_argument(
        "--iter",
        help="Number of iterations for SA algorithm, default=100",
        type=int,
        default=100,
    )
    parser_selector.add_argument(
        "--alpha",
        help="Alpha value for SA algorithm, default=0.99",
        type=float,
        default=0.99,
    )
    parser_selector.add_argument(
        "--seed",
        help="Random seed for selector, default=None",
        type=int,
        default=None,
    )
    parser_selector.set_defaults(func=select_data.main)

    parser_visualizer = subparsers.add_parser(
        "visualizer", help="Visualize network generated by CWNET"
    )
    parser_visualizer.add_argument(
        "-i", "--input", help="Input result file of CWNET", required=True
    )
    parser_visualizer.add_argument(
        "-o", "--output", help="Output picture file of network", required=True
    )
    parser_visualizer.add_argument(
        "--predicted_only",
        help="Nodes and edges only contained in predicted sample would be drawn, default=False",
        action="store_true",
    )
    parser_visualizer.add_argument(
        "--highlight_color",
        help='Color for select nodes and edges, default="orange"',
        default="orange",
    )
    parser_visualizer.add_argument(
        "--node_cmap", help='Colormap for nodes, default="Greens"', default="Greens"
    )
    parser_visualizer.add_argument(
        "--edge_cmap", help='Colormap for edges, default="Greens"', default="Greens"
    )
    parser_visualizer.add_argument(
        "--node_ratio",
        help="Ratio of node size, higher means smaller node size, default=3.0",
        type=float,
        default=600.0,
    )
    parser_visualizer.add_argument(
        "--edge_ratio",
        help="Ratio of edge width, higher means thinner edge width, default=20.0",
        type=float,
        default=3.0,
    )
    parser_visualizer.add_argument(
        "--lower",
        help="Means lower phenotype is better, if this parameter is setting",
        action="store_true",
    )
    parser_visualizer.add_argument(
        "--label_top_nodes",
        help="Number and legend top-N nodes " "by weight value, (default=-1 not set)",
        type=int,
        default=-1,
    )
    parser_visualizer.add_argument(
        "--label_top_edges",
        help="Number and legend top-N edges " "by weight value, (default=-1 not set)",
        type=int,
        default=-1,
    )
    parser_visualizer.add_argument(
        "--edge_alpha_min",
        help="Minimum alpha for weakest edges " "(default=0.06)",
        type=float,
        default=0.06,
    )
    parser_visualizer.add_argument(
        "--draw_top_nodes",
        help="If set, only draw the top-N nodes"
        " (by weight) and extra nodes from top-N edges,"
        " (default=-1 draw all)",
        type=int,
        default=-1,
    )
    parser_visualizer.add_argument(
        "--draw_top_edges",
        help="If set, only draw the top-N edges (by weight), "
        "if not set and --draw_top_nodes set, set to the same value of draw_top_nodes,"
        " (default=-1 draw all)",
        type=int,
        default=-1,
    )

    parser_visualizer.set_defaults(func=visualize_data.main)


def main(opts):
    opts.func(opts)
