from gpnet.io.message import Message
from os import getpid
from gpnet.simulator.calc import calc_pheno
from gpnet.lib import fast_ridge
from gpnet.algorithm.SA import SA
import numpy as np
from gpnet.io.data_io import DataLoader, DataSaver
import pickle


class CWNET_FR:
    def __init__(
        self,
        in_file,
        weight_file,
        is_lower_better,
        is_normalization,
        is_store_iter,
        top_edges,
        min_edge_cnt,
        step_size,
        iter_cnt,
        iter_alpha,
        seed,
        out_file,
    ):
        self.__in_file = in_file
        self.__weight_file = weight_file
        self.__is_lower_better = is_lower_better
        self.__is_store_iter = is_store_iter
        self.__out_file = out_file
        self.__out_model = out_file + ".bin"
        self.__type_info = None
        self.__allele_name = None
        self.__top_edges = top_edges
        self.__step_size = step_size
        self.__iter = iter_cnt
        self.__alpha = iter_alpha
        self.__seed = seed
        self.__min_edge_cnt = min_edge_cnt
        self.__model = None

        self.__node_w = None
        self.__edge_w = None
        self.__select_edges = None

    def predict(self, data):
        return self.__model.predict(np.array([data], dtype=np.int8))[0]

    def __fast_ridge(self, genotypes, phenotypes):
        X_train = np.array(genotypes, dtype=np.int8)
        y_train = np.array(phenotypes, dtype=np.float64)
        M, K = X_train.shape
        Message.info(f"\tTrain loaded: M={M}, K={K}")

        model = fast_ridge.GraphModel()

        Message.info(
            f"\tFitting model (Auto Edge Selection: Max={self.__top_edges}, Step={self.__step_size})..."
        )

        a1, a2, best_k = model.fit(
            X_train,
            y_train,
            self.__top_edges,
            self.__step_size,
            self.__min_edge_cnt,
            threads=1,
        )

        Message.info(f"\tTraining finished")
        Message.info(f"\t\t[Auto Result] Stage1 Alpha: {a1:.6g}")
        Message.info(f"\t\t[Auto Result] Final Alpha:  {a2:.6g}")
        Message.info(
            f"\t\t[Auto Result] Best Edges:   {best_k} (out of max {self.__top_edges})"
        )

        self.__node_w = model.get_node_weights()
        self.__edge_w = model.get_edge_weights()
        self.__selected_edges = model.get_selected_edges()
        Message.info(f"\tSelected {len(self.__selected_edges)} edges.")

        self.__model = model

    def _get_node_edge_weight(self):
        node_weight = []
        edge_weight = []

        for i, w in enumerate(self.__node_w):
            node_weight.append([self.__allele_name[i], w])

        for (u, v), w in zip(self.__selected_edges, self.__edge_w):
            edge_weight.append([self.__allele_name[u], self.__allele_name[v], w])

        # generate additional information of weight of nodes and weight of edges, sorted by weight descend
        additional_info = ["#\n# Nodes weights"]
        for _ in sorted(
            node_weight, key=lambda x: x[-1], reverse=(not self.__is_lower_better)
        ):
            additional_info.append("# %s" % (" ".join(map(str, _))))

        additional_info.append("#\n# Edges weights")
        for _ in sorted(
            edge_weight, key=lambda x: x[-1], reverse=(not self.__is_lower_better)
        ):
            additional_info.append("# %s" % (" ".join(map(str, _))))

        return additional_info

    def run(self):
        Message.info("\tPID:%d Loading data" % getpid())
        dl = DataLoader()
        dl.load_genotype(self.__in_file)
        genotypes = dl.genotypes
        phenotypes = dl.phenotypes
        self.__type_info = dl.type_info
        self.__allele_name = dl.allele_name

        Message.info("\tPID:%d Running fast ridge" % getpid())
        self.__fast_ridge(genotypes, phenotypes)

        self.__model.dump(self.__out_model)

        Message.info("\tPID:%d Running SA" % getpid())
        sa = SA(
            self.__type_info,
            self.__allele_name,
            self.__out_file,
            self.predict,
            self.__is_lower_better,
            self.__is_store_iter,
            iterate=self.__iter,
            alpha=self.__alpha,
            seed=self.__seed,
        )
        sa.run()

        best_sa_data = sa.data

        # best_sa_pheno can only be calculated while data is generated by gpnet.py simulator
        if self.__weight_file:
            dl.load_weight_data(self.__weight_file)
            single_weight = dl.single_weight
            multi_weight = dl.multi_weight
            best_sa_pheno = calc_pheno(best_sa_data, single_weight, multi_weight)
        else:
            best_sa_pheno = "Not support"

        Message.info("\tPID:%d Saving predict data" % getpid())
        ds = DataSaver(self.__out_file)
        ds.save_data(
            self.__type_info,
            self.__allele_name,
            [best_sa_data],
            [best_sa_pheno],
            self._get_node_edge_weight(),
        )
