from sklearn.linear_model import LinearRegression
import pickle
from gpnet.simulator.calc import calc_pheno
from gpnet.algorithm.SA import SA
from gpnet.algorithm.GA import GA
from gpnet.io.data_io import DataLoader, DataSaver
from gpnet.io.message import Message
from os import getpid


class MLR:
    def __init__(
        self,
        in_file,
        weight_file,
        is_lower_better,
        is_normalization,
        is_store_iter,
        top_edges,
        min_edge_cnt,
        step_size,
        optim_args,
        seed,
        out_file,
    ):
        self.__in_file = in_file
        self.__weight_file = weight_file
        self.__is_lower_better = is_lower_better
        self.__is_store_iter = is_store_iter
        self.__optim_args = optim_args
        self.__seed = seed
        self.__out_file = out_file
        self.__out_model = out_file + ".pkl"
        self.__type_info = None
        self.__allele_name = None
        self.__lrg = LinearRegression()
        self.__model = None

    def predict(self, data):
        return self.__model.predict([data])[0]

    def _get_node_coefficients(self):
        node_coefficients = []

        for _ in range(len(self.__allele_name)):
            node_coefficients.append([self.__allele_name[_], self.__lrg.coef_[_]])

        # generate additional information of coefficients of each site, sorted by coefficients descend
        additional_info = ["#\n# Nodes coefficients"]
        for _ in sorted(
            node_coefficients, key=lambda x: x[-1], reverse=(not self.__is_lower_better)
        ):
            additional_info.append("# %s" % (" ".join(map(str, _))))

        return additional_info

    def run(self):
        Message.info("\tPID:%d Loading data" % getpid())
        dl = DataLoader()
        dl.load_genotype(self.__in_file)
        genotypes = dl.genotypes
        phenotypes = dl.phenotypes
        self.__type_info = dl.type_info
        self.__allele_name = dl.allele_name

        Message.info("\tPID:%d Starting multi linear regression" % getpid())
        x_train = genotypes
        y_train = phenotypes
        self.__model = self.__lrg.fit(x_train, y_train)
        with open(self.__out_model, "wb") as fout:
            pickle.dump(self.__model, fout)

        Message.info("\tPID:%d Running Optimization" % getpid())
        if self.__optim_args["Method"] == "SA":
            sa = SA(
                self.__type_info,
                self.__allele_name,
                self.__out_file,
                self.predict,
                self.__is_lower_better,
                self.__is_store_iter,
                iterate=self.__optim_args["iter_cnt"],
                alpha=self.__optim_args["iter_alpha"],
                seed=self.__seed,
            )
            sa.run()
            best_data = sa.data
        elif self.__optim_args["Method"] == "GA":
            ga = GA(
                self.__type_info,
                self.__allele_name,
                self.__out_file,
                self.predict,
                self.__is_lower_better,
                self.__is_store_iter,
                n_generations=self.__optim_args["n_generations"],
                pop_size=self.__optim_args["pop_size"],
                cross_rate=self.__optim_args["cross_rate"],
                mutation_rate=self.__optim_args["mutation_rate"],
                seed=self.__seed,
            )
            ga.run()
            best_data = ga.data

        # best_pheno can only be calculated while data is generated by gpnet.py simulator
        if self.__weight_file:
            dl.load_weight_data(self.__weight_file)
            single_weight = dl.single_weight
            multi_weight = dl.multi_weight
            best_pheno = calc_pheno(best_data, single_weight, multi_weight)
        else:
            best_pheno = "Not support"

        Message.info("\tPID:%d Saving predict data" % getpid())
        ds = DataSaver(self.__out_file)
        ds.save_data(
            self.__type_info,
            self.__allele_name,
            [best_data],
            [best_pheno],
            self._get_node_coefficients(),
        )
